Repository LLNL/ExaCA, pull requests merged in 2024-05, with the labels that each got.

#337 Allocate size of parsed string in splitString
  src/CAparsefiles.cpp
Labels: bug

#339 Remove hardcoded initial octahedron size for nucleated grains
  src/CAupdate.hpp
Labels: bug

#340 Fix timers min/max mistake
  src/CAtimers.hpp
Labels: bug

#344 Formatting of json string for output SubstrateFilename
  src/CAinputs.hpp
  unit_test/tstInputs.hpp
Labels: bug

#351 Make sure all grid inputs for json write/read test are initialized
  unit_test/tstInputs.hpp
Labels: bug-ception

#346 Elimination of redundant memory access and calculations in cell capture
  src/CAupdate.hpp
Labels: performance
